### ISSUE TITLE
Modify Settings cannot be saved

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#104]
Create a collection.
Modify Settings > change the Description to "my description1" > click on "Top" next to "Title and URLs" > scroll up and click on "Save".
Nothing happens. Changes were not saved.
Do it similar:
Modify Settings > change the Description to "my description2" > DO NOT click on "Top" next to "Title and URLs" > scroll up and click on "Save".
Now it is beeing saved.

So something happens by clicking on "Top" on the page.

**Comment by ewg118** [comment]
This is very strange. I've tested this on both Chrome and Firefox and clicking on the "Top" link doesn't prevent saving.

**Comment by Msch0150** [comment]
Hm, ok. 
Then it might be a personal issue. No problem, I have a workaround. 
Let's accept this and concentrate on other stuff.
Thanks for testing it.

"Once" I have free time I will try to debug it.

**Comment by Msch0150** [comment]
Tried to duplicate it after a reinstallation. All works as expected.

I am closing this a non-reproducible. Sorry for inconvenience.
