### ISSUE TITLE
Translation, meaning of "identifier"

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#109]
Numishare > Admin UI > <coin> > Administrative > +Identifier > "my_identifier"
Publish the coin. The english page displays:

**Identifier**: my_identifier

The German page displays:

**Bestimmt von**: my_identifier

The meaning of the German "Bestimmt von" is equal to "identified by" or "determined by", but it not the meaning of an inventory number.
But a look to "http://nomisma.org/nuds#identifier" shows:

The <identifier> is the holding repository's internal identification number--typically an accession number. If the <identifier> may be expressed in a way that is valid for a URI, it is recommended that this number be simultaneously used as the <recordId> in the <control> of the NUDS record.

So this meaning expects more a inventory-number than a person. In this case the translation is misleading.

**Comment by ewg118** [comment]
Yes, that's correct. The "Identifier" should refer to the inventory or accession number. The Berlin database uses "Objektnummer". Is this generic enough? Different museums have slightly different vocabulary for the same thing. The British Museum uses "Registration number."

**Comment by Msch0150** [comment]
I think "Objektnummer" is quite ok.

**Comment by Msch0150** [comment]
Hm. I took a deeper look. Berlin uses "Inventarnummer" in addition to "Objektnummer". Example:

https://ikmk.smb.museum/object?lang=de&id=18268161


Many Universities use "Inventarnummer" next to "Objektnummer", a few examples:

University Rostok:
https://numid.uni-rostock.de/object?lang=de&id=ID173

Goethe Universität Frankfurt:
http://www.mkfrankfurt.uni-frankfurt.de/object?id=ID294

Ruhr-Universität Bochum:
http://ikmk.ruhr-uni-bochum.de/object?id=ID410

Based on the the description in "http://nomisma.org/nuds#identifier" the term "Inventarnummer" would fit better. But maybe another meaning would help.
