### ISSUE TITLE
Wrong character after Obverse and Reverse in german version

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#112]
Example:

http://numismatics.org/collection/1944.100.13245?lang=en

Below the image you see the obverse legend and description:

**Obverse: IVL CRIS-PVS NOB C - Head laureate right** 

If you check the German version:

http://numismatics.org/collection/1944.100.13245?lang=de

**Vorderseite; IVL CRIS-PVS NOB C - Head laureate right** 

Like the english version, the char should be a ":" instead of a ";".
The same bad character is visible for the Revers/Rückseite.

Info: other languages like "fr", "nl" and "it" look ok.

**Comment by ewg118** [comment]
Ah, I think I placed the semicolon in the incorrect place in the record page. I was requested to replace the hyphen with semicolon separating the legend and type description for the Swiss National Museum, which was suggested for all German-language changes.

**Comment by Msch0150** [comment]
Works! Thanks.
