### ISSUE TITLE
Wrong date for RIC ²I 161

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#113]
This is a content issue:

http://numismatics.org/ocre/id/ric.1(2).aug.161

shows a date range: 15 BC - 13 BC 

But it should be AD 10 - AD 14  like for http://numismatics.org/ocre/id/ric.1(2).aug.160.

**Comment by ewg118** [comment]
I have updated the record in OCRE on the our new Amazon server, so the change will be visible when we change the DNS over in the next week or two. If you encounter other errors in the underlying OCRE data, can you submit them in the feedback form in OCRE? That way the error report goes directly to the Roman curator who can fix it more directly.

**Comment by Msch0150** [comment]
Yes, that is even better. I just submitted one.
Some others will follow.
