### ISSUE TITLE
Is it possible to add new fields or remove existing ones?

### ISSUE THREAD

**Issue by fgnm** [ewg118/numishare#127]
Hi Ethan,
I was wondering if and how could be possible to extend the existing numishare structure by adding or removing fields in the coin description form. For a University project, there's the need to customize some coin descriptions to fit the standard in our country (Italy).
Is it possible to edit fields easly, how?

Many thanks!

**Comment by ewg118** [comment]
New fields could be added to the editing interface, but the model might be incompatible with the NUDS schema and therefore difficult to interchange with data from other systems. The first step would be to come up with a list of your specifications and then see how the schema can be extended to accommodate your specs, and then the editing form can be adjusted as necessary.

The Numishare front end should display the new data, although you might want to change the code if you want the new data laid out in a certain way in the browser

**Comment by ewg118** [comment]
Closing pending the updating of the `nuds:findspotDesc` for new contextual fields.
