### ISSUE TITLE
Filtering for secondaryTreatment

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#135]
I created a couple of halved coins in a collection.
The xml structure look like:

```
<ns0:physDesc>
  <ns0:measurementsSet>
    <ns0:weight>5.374</ns0:weight>
    <ns0:thickness>4.24</ns0:thickness>
  </ns0:measurementsSet>
  <ns0:conservationState>
    <ns0:secondaryTreatment ns2:type="simple" ns2:href="http://nomisma.org/id/halved">Halved</ns0:secondaryTreatment>
    <ns0:obverse>
      <ns0:wear ns2:type="simple" ns2:href="http://nomisma.org/id/wear_undetermined">Wear undetermined</ns0:wear>
      <ns0:condition ns2:type="simple" ns2:href="http://nomisma.org/id/extremely_corroded">Extremely corroded</ns0:condition>
    </ns0:obverse>
    <ns0:reverse>
      <ns0:wear ns2:type="simple" ns2:href="http://nomisma.org/id/wear_undetermined">Wear undetermined</ns0:wear>
      <ns0:condition ns2:type="simple" ns2:href="http://nomisma.org/id/extremely_corroded">Extremely corroded</ns0:condition>
    </ns0:reverse>
  </ns0:conservationState>
</ns0:physDesc>
```

In the front end I do see the a link "Halved":

Secondary Treatment: [Halved](http://myserver.domain/cf/results?q=secondaryTreatment_facet:%22Halved%22&lang=en)

I can click on it but the resulting "Filters" page doesn't list any item:
Filters 
Secondary Treatment: Halved
No results found. Start over.

I already added "secondaryTreatment_facet" to the facets in the admin-UI. I found /ui/xslt/templates-search.xsl and added it to the three lists of search-items. But that is probably for the "search" drop-down menus only.
Maybe it needs to be added somewhere else as well. Do you have a hint for me?

**Comment by ewg118** [comment]
The fields within `nuds:conservationState` were not indexed into Solr for free text or faceted search. I have now updated the XSLT stylesheets. You'll have to republish the affected objects in Solr before the facet drop down appears on the browse page. I'm not able to test the change since I don't have any data. So after checking out the code, please append .solr to the object URL in Numishare and let me know if you see a `secondaryTreatment_facet` field in the XML for Solr.

**Comment by Msch0150** [comment]
Now it looks better. 
I works perfectly when the language is set to "English", but it does not work if the language is set to "German".

On the UI for a coin:
Erhaltungszustand
    Nachbehandlung: [halbiert](http://myserver.domain/cf/results?q=secondaryTreatment_facet:%22halbiert%22&lang=de)

Does not find any objects:

Filter
Nachbehandlung: halbiert
No results found. [Start over.]

The vv.2021.1058.015-999.solr looks like:
```
<field name="id">vv.2021.1058.015-999</field>
...
<field name="secondaryTreatment_facet">Halved</field>
<field name="secondaryTreatment_text">Halved</field>
<field name="secondaryTreatment_uri">http://nomisma.org/id/halved</field>
<field name="secondaryTreatment_match_uri">https://ikmk.smb.museum/ndp/secondaryTreatment/15</field>
<field name="wear_facet">Wear undetermined</field>
<field name="wear_text">Wear undetermined</field>
<field name="wear_uri">http://nomisma.org/id/wear_undetermined</field>
<field name="wear_text">W 0</field>
...
<field name="id">vv.2021.1058.015-999-de</field>
...
<field name="secondaryTreatment_facet">Halved</field>
<field name="secondaryTreatment_text">Halved</field>
<field name="secondaryTreatment_uri">http://nomisma.org/id/halved</field>
<field name="secondaryTreatment_match_uri">https://ikmk.smb.museum/ndp/secondaryTreatment/15</field>
<field name="wear_facet">Wear undetermined</field>
<field name="wear_text">Wear undetermined</field>
<field name="wear_uri">http://nomisma.org/id/wear_undetermined</field>
<field name="wear_text">W 0</field>
...
<field name="id">vv.2021.1058.015-999-en</field>
...
<field name="secondaryTreatment_facet">Halved</field>
<field name="secondaryTreatment_text">Halved</field>
<field name="secondaryTreatment_uri">http://nomisma.org/id/halved</field>
<field name="secondaryTreatment_match_uri">https://ikmk.smb.museum/ndp/secondaryTreatment/15</field>
<field name="wear_facet">Wear undetermined</field>
<field name="wear_text">Wear undetermined</field>
<field name="wear_uri">http://nomisma.org/id/wear_undetermined</field>
<field name="wear_text">W 0</field>
...
```

It looks like that the values for "secondaryTreatment_facet" and "secondaryTreatment_text" are not translated for the "vv.2021.1058.015-999-de" fields.
