### ISSUE TITLE
Manual Findspot coordinates seems not working

### ISSUE THREAD

**Issue by fgnm** [ewg118/numishare#136]
Hi Ethan!
While testing a new installation of numishare (based on latest commit) I noticed that when set the findspot to manual coordinates information don't appears on the map nor in any kind of export, while if I set them with Geonames it works. Is there something I need to enable first/setup first to enable manual coordinates?
Thanks

**Comment by ewg118** [comment]
I see in the NUDS->GeoJSON XSLT where the manual coordinates are not being represented. However, the NUDS model uses gml:coordinates, which has been deprecated and replaced with gml:pos. How many coins have you entered with manual coordinates? If it's not many, I should transition to the current GML schema and update the XForms backend and XSLT stylesheets accordingly.

**Comment by fgnm** [comment]
Many thanks! Currently, I'm just testing all functionalities, so only some tests has been done. If this could be fixed would be very appreciate :)

**Comment by ewg118** [comment]
OK, I have updated the model. Now when you insert manual coordinates, the GML structure of `gml:location/gml:Point/gml:pos` is created, following the model already established for coordinates within `nuds:findspot/nuds:fallsWithin` to manually embed coordinates extracted from gazetteer systems like Geonames or Wikidata. All of the different serializations that rely on the new GML model have been updated, so the coordinates should now be visible in the maps with GeoJSON and be indexed into Solr for the map browsing interfaces.

**Comment by fgnm** [comment]
Thanks so much for the quick fix! It works well expect for the coin details page in which the map isn't still visible with manual coordinates, but I confirm that in the main `Maps` section I can now see the manual findspots.

**Comment by ewg118** [comment]
If you append ".geojson" to the coin URI, are the coordinates in the
GeoJSON?

Does your coin point to a Nomisma URI for the mint, so you can confirm that
the mint point is visible?

**Comment by fgnm** [comment]
Yes, I can see the coordinates using `.geojson`, and the map appears when the mint field is provided (I can see both mint and findspot in the map btw). I don't know if it's a bug or an intended behavior, but the map doesn't show when only the findspot is provided.

**Comment by ewg118** [comment]
OK, I'll look into that.

**Comment by ewg118** [comment]
OK, try again now with only a findspot and not a mint.

**Comment by fgnm** [comment]
Perfect! Thank you :)
