### ISSUE TITLE
Commit overwrote changes

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#140]
It looks like that commit:

https://github.com/ewg118/numishare/commit/077f6affd3637c9bb0b32c08b738c11551bfd913

supplied translations for https://github.com/ewg118/numishare/issues/110 and https://github.com/ewg118/numishare/issues/130 but it looks like that it also removed previous changes probably by accident:

https://github.com/ewg118/numishare/commit/d5651af9aab1a025726024b9799f8546eb528cb8
https://github.com/ewg118/numishare/commit/d5c4f022b031379005636ce9bb0744d6a8775e8d
https://github.com/ewg118/numishare/commit/eac8ea525d3b095c64fb72e84db08682f123b7ca
https://github.com/ewg118/numishare/commit/e4ac928f742469d1a7761038ecb871782bc6d583

**Comment by ewg118** [comment]
I'm not sure how that happened, exactly. They are restored.
