### ISSUE TITLE
Order of cointype collection items

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#144]
Info: I have in my mind that this worked in the past ...

Simplified method to demonstrate the behavoiur:

I have a cointype-collection.
The items are all sortable like "coin.01.xml", coin.02.xml", ...
I do upload them to the DB in that order.
The items appear in the correct order in the Numishare admin UI.
If I publish the coins one by one, then I do see the correct order in the public UI (browse).
coin.01 > coin.02 > coin.03 > coin.04 > ...
But once I reach and publish coin.10.xml then suddenly the order in the public UI (browse) got messed up:
coin.03 > coin.08 > coin.05 > coin.09 >  coin.02 > coin.01 > coin.06 > coin.04 > coin.07 > coin.10
Strange. The order in the admin UI is still OK. The order in the Exist DB is OK as well.

Of course I want a well ordered list by default in the public UI, like https://numismatics.org/ocre/results.

Do you have any idea what can cause this and how to get rid of that problem?

**Comment by ewg118** [comment]
The default sort order of records in Solr seems to be a black box. It may correspond to the date the record was indexed, and the "publish all" link doesn't necessarily batch NUDS records together from the eXist XML database that are sequential.

There is a way to cheat this, however, but indexing a sortable ID as a Solr field called `sortId`. You can put this into your NUDS document in the `control` as an `<otherRecordId localtype="sortId">00001</otherRecordId>` and it will be indexed into Solr. See the underlying XML for https://numismatics.org/bigr/id/bigr.diodotus_i_ii.1.xml

It's also possible to generate the `sortId` Solr field in the NUDS->Solr XSLT stylesheet. This was the original method for ordering OCRE, CRRO, etc., but I think putting the sortId directly into the NUDS file is more sustainable, as it doesn't require you to modify any code in Numishare. When you use OCRE and other projects, and the sort request parameter has not been explicitly set, the underlying Numishare code appends `&sort=sortId asc` to the Solr query.

**Comment by Msch0150** [comment]
The method " <otherRecordId localtype="sortId">00001</otherRecordId> " works quite well. Many thanks for the hint!
