### ISSUE TITLE
CRRO Not working!

### ISSUE THREAD

**Issue by sumregina23** [ewg118/numishare#35]
Hi,

I'm trying to use the CRRO, but I'm getting an Orbeon error. The CHRR works, but if you try to click on an individual coin, it takes you to the same Orbeon error.  Please fix! 

Thank you from a desperate PhD student in the final stages of the dissertation.

Here is the error:

Orbeon Forms - An Error has Occurred

An error has occurred in Orbeon Forms. You may want to try one of the following:

If this error occurred when you followed a link, press your browser's Back button.
If the above does not work, try reloading the page:
With Firefox: hold down the shift key and click the Reload button in your browser toolbar.
With Safari and Chrome: click the Reload button in your browser toolbar.
With Internet Explorer: hold down the control key and click the Reload button in your browser toolbar.
Return home.
Orbeon Forms 4.5.0.201404080036 CE

**Comment by ewg118** [comment]
This has been fixed. Part of the database corrupted yesterday, and I had to restore it.
