### ISSUE TITLE
Supported versions

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#43]
Is there any support matrix? I setup the numishare on Windows 10.

tomcat 8
solr 4.10 (solr 5.0 and higher didn't work, in addition I had to copy example\lib\ext\* to tomcat\lib\)
exist 4.0.0 (needed to manually copy from current betterFORM resources\xslt\*.xsl to webapp\exist\WEB-INF\classes\META-INF\resource\ , same with exist 3.6)
orbeon 2017.2.201712300816-CE

I got the application to work. I can login, I can create a collection, I can create coins. I can search, I can browse but I cannot display the main page of the created collection like:

http://localhost:8080/orbeon/numishare/UlpiaCol/

Orbeon Forms - An Error has Occurred
An error has occurred in Orbeon Forms. You may want to try one of the following:
    If this error occurred when you followed a link, press your browser's Back button.
    If the above does not work, try reloading the page:
        With Firefox: hold down the shift key and click the Reload button in your browser toolbar.
        With Safari and Chrome: click the Reload button in your browser toolbar.
        With Internet Explorer: hold down the control key and click the Reload button in your browser toolbar. 
    Return home.

I attached the orbeon.log.

I read in the Wiki that numishare is tested with solr 4.10 only. The latest version is 7.2.1. So, maybe the root cause is the usage of some newer software. Also the manual copy action to get exist-db to work might be a root cause. A list of tested versions might help. 
[orbeon.log](https://github.com/ewg118/numishare/files/1800753/orbeon.log)

**Comment by Msch0150** [comment]
Additional info: java 1.8.0

**Comment by ewg118** [comment]
This was a bug reported with the index page related specifically to the "featured object" code to display a random published coin on the home page. A workaround was to remove this code from the XML Pipeline and in index XSLT file. I finally sat down and worked through the issue, and I believe it should be resolved now. You'll want to pull updates from Github because several files are affected.

**Comment by Msch0150** [comment]
Cool, works now. Very fast solution! Thanks a lot.
