### ISSUE TITLE
Empty "Digital Representation"

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#44]
Setup described in https://github.com/ewg118/numishare/issues/43

Create/Edit Coin > +Digital Representation > Digital Representations 
I do see "Digital Representations x"
I assume that I should see some fields for adding images ...
But all is "blank" below "Digital Representations x". No errors in the logs. Only some warning in orbeon.log:

2018-03-13 19:17:59,333 INFO  ProcessorService  - /numishare/admin/edit/coin/ - Received request
2018-03-13 19:17:59,595 INFO  lifecycle  - event: {"request": "244", "session": "99726F6A7D2DD5EB77027AADDE2A9BEF", "source": "xforms", "message": "new form session", "uuid": "dac63a39096c557d664f6da511c19fff8b2a92e5"}
2018-03-13 19:18:00,125 WARN  ResponseProcessCookies  - Cookie rejected [JSESSIONID="3F1AF39641CCC1FFF46E803EABACC5D3", version:0, domain:nomisma.org, path:/orbeon/, expiry:null] Illegal path attribute "/orbeon/". Path of origin: "/feed/"
2018-03-13 19:18:00,454 WARN  ResponseProcessCookies  - Cookie rejected [JSESSIONID="19AC05C1E9D13093A80D349CEAFD55AB", version:0, domain:nomisma.org, path:/orbeon/, expiry:null] Illegal path attribute "/orbeon/". Path of origin: "/feed/"
2018-03-13 19:18:00,653 WARN  ResponseProcessCookies  - Cookie rejected [JSESSIONID="44EA713122285725388B8C076B525DAA", version:0, domain:nomisma.org, path:/orbeon/, expiry:null] Illegal path attribute "/orbeon/". Path of origin: "/feed/"
2018-03-13 19:18:00,981 INFO  lifecycle  - event: {"request": "244", "session": "99726F6A7D2DD5EB77027AADDE2A9BEF", "source": "xforms", "message": "after cacheOrStore", "document cache current size": "30", "document cache max size": "50"}
2018-03-13 19:18:01,303 INFO  ProcessorService  - /numishare/admin/edit/coin/ - Timing: 1970

Test browsers: FireFox 58.02 (64Bit) and Chrome Version 64.0.3282.186 (Official Build) (64-bit)

If I turn on the debugger, I do see: 
Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6

I attached a screenshot:
![digital_representation_blank](https://user-images.githubusercontent.com/37273467/37361728-dedef192-26f3-11e8-9851-c3f7fbb9b67a.JPG)

**Comment by ewg118** [comment]
I will take a look at this, but image uploads are no longer supported, and the digital representation sections of records are never manually edited in other projects. At best, I can create inputs in the web form to copy and paste absolute URLs to files stored on a web server.

**Comment by Msch0150** [comment]
Maybe a misunderstanding. For a coin like:
http://numismatics.org/collection/1944.100.20611
you see the obverse and reverse image.
I want to see images like them as well for the entered coins here, but so far I have not seen any location in the admin menu where to place the links to the images.

**Comment by Msch0150** [comment]
Additional info: I am using the master branch. Do I have to use the mantis2 branch?

**Comment by ewg118** [comment]
I'm a bit confused: are you attempting to mirror the ANS database? It would be possible harvest our data without manually re-entering anything.

**Comment by Msch0150** [comment]
I need to add coins from a couple of different findspots in Germany into a "standard" system which makes it possible to compare them to create reports .... For most of the coins we do have images available which should be visible when I select the coin. Same function as with the above example from ANS. So ANS has attached or referenced images to a coin. I just what to use the same function. How has ANS assigned images to objects? Probably very simple, but so far I haven't found a way to do it yet.

**Comment by Msch0150** [comment]
Indeed it looks like a misunderstanding. I thought numishare provides a UI which can be used to enter all available NUDS entires. But that doesn't seem to be the case. 
So, yes, it would be very helpful to get input fields in the form to enter absolute path to the images.

**Comment by ewg118** [comment]
I'm leaving for a conference today and will be gone all week. I will try to get to this and the other issue after I return. The numishare backend is never used for editing Mantis, and so it isn't as refined as the front end, and not as well tested. I am hoping to fix a lot of these issues in the next six months since there are two other projects that want to use numishare. So I appreciate your feedback and will try to fix whatever bugs you find

**Comment by Msch0150** [comment]
Now I am able to add Digital Reprensentations (thank you very much). 
Combined > Reference: "http://numismatics.org/collectionimages/19001949/1944/1944.100.20611.rev.width175.jpg"
Thumbnail: "http://numismatics.org/collectionimages/19001949/1944/1944.100.20611.rev.width175.jpg"
(Info: IIIF Service is expandable but does display anything)
Save. > Return > click on HTML view of the modified coin > The usual information page is displayed, but there is no image visible, I assume it should be displayed.
Additional info: click on NUDS/XML > The XML file shows the correct values:
...
</descMeta>
<digRep>
<mets:fileSec xmlns:mets="http://www.loc.gov/METS/">
<mets:fileGrp USE="combined">
<mets:file USE="thumbnail" MIMETYPE="image/jpeg">
<mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="http://numismatics.org/collectionimages/19001949/1944/1944.100.20611.rev.width175.jpg"/>
</mets:file>
<mets:file USE="reference" MIMETYPE="image/jpeg">
<mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="http://numismatics.org/collectionimages/19001949/1944/1944.100.20611.rev.width350.jpg"/>
</mets:file>
</mets:fileGrp>
</mets:fileSec>
</digRep>
</nuds>

**Comment by ewg118** [comment]
You will want to insert obverse and reverse images. The UI is not set up to accommodate images that have the obverse and reverse combined into one file.

**Comment by Msch0150** [comment]
Works! Thanks.
