### ISSUE TITLE
Clickable References

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#51]
I need to add a clickable reference like seen in:

http://numismatics.org/collection/1944.100.39727

There are three clickable references defined (RIC I (second edition) Nero 354; BMC.113; WCN.171).
When using:
Edit coin > +Reference Description > References > +Reference:
"+Identifier" and a Title filed appears.
I can enter anything in the title field but it doesn't appear as a link, here I would like that a Link to the OCRE appears, but I havn't found a method which works.
Info: "+Identifier" doesn't show any reaction.

**Comment by ewg118** [comment]
The reference element has been migrated to the current XSD, where the title and idenfifier are in the TEI namespace. This will resolve carriage return issues. Clickable references are not supported in the editor, and there is no timeline to support this. The typological description section allows you to provide a URI to an ANS-published coin type, and it will pull information dynamically from OCRE, PELLA, etc.
