### ISSUE TITLE
Error getting Solr document from XQuery ingestion pipeline.

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#52]
Create a new collection. Create a new coin for the collection.
Click on "Admin Home" > publish the coin manually by clicking the checkbox the the right side.
(Info: if you click on the coin, then the status of the coin is "approved".)
Click "unpublish all objects".
(Info: if you click on the coin, then the status of the coin is still "approved".)
Click "Publish all approved objects".
Now the error occurs:

Error getting Solr document from XQuery ingestion pipeline.

Info: 
Tested with solr 4.10.4 and solr 6.6.3 in 5.5.5 emulation mode.

**Comment by Msch0150** [comment]
Additional info: I could not see any errors in the log files.

**Comment by ewg118** [comment]
This is probably due to some issue with the NUDS file's transformation into Solr XML, but it's hard to know without checking the log. If you append .solr onto the URL for the coin, it will initiate the transformation, which will result in an error in the orbeon log.

**Comment by Msch0150** [comment]
If I add ".solr" to the URL of a displayed coin, then I get a valid XML structure.
I think it is not an error of an individual coin, because I can publish each individual coin one by one via the UI. The error occurs only if i use the link "Publish All Approved Objects".

**Comment by Msch0150** [comment]
It looks like that aggregate-ids.xql is not transfered to the exist database.

The exist DB is running in a separate container (db). The tomcat with numishare and orbeon is running in a separate container as well (web). The exist-config.xml points to the DB via:

<url>http://db:8080/exist/rest/db/</url>

Where "db" is the internal name to connect to the container.
So far, so good. Now force the issue:

Create a new collection. Create a new coin for the collection.
Click on "Admin Home" > publish the coin manually by clicking the checkbox the the right side.
(Info: if you click on the coin, then the status of the coin is "approved".)
Click "unpublish all objects".
(Info: if you click on the coin, then the status of the coin is still "approved".)
Click "Publish all approved objects".
Now the error occurs:

Error getting Solr document from XQuery ingestion pipeline.

The orbeon.log shows:

2018-07-15 11:08:12,148 INFO  ProcessorService  - /numishare/test02/ingest - Received request
2018-07-15 11:08:12,177 INFO  PageFlowControllerProcessor  - not found {controller: "oxf:/apps/numishare/page-flow.xml", method: "GET", path: "/numishare/test02/ingest", resource: "http://db:8080/exist/rest/db/test02/aggregate-ids.xql?identifiers=69ce1feb43"}
2018-07-15 11:08:12,178 INFO  PageFlowControllerProcessor  - not found {controller: "oxf:/page-flow.xml", method: "GET", path: "/numishare/test02/ingest", resource: "http://db:8080/exist/rest/db/test02/aggregate-ids.xql?identifiers=69ce1feb43"}
2018-07-15 11:08:12,187 INFO  ProcessorService  - /numishare/test02/ingest - Timing: 39
2018-07-15 11:08:12,188 INFO  lifecycle  - event: {"request": "111", "session": "0B8FD12726BA2A4B08170E31E92AAC55", "source": "service", "message": "end: handle", "time": "40 ms"}
2018-07-15 11:08:12,189 ERROR XFormsServer  - xforms-submit-error - xf:submission for submission id: generate-add-document, error code received when submitting instance: 404

I checked the DB. The file "aggregate-ids.xql" does not exist in the folder of the collection (http://db:8080/exist/rest/db/test02/)
If I add the file "aggregate-ids.xql" manually into the folder of the collection via the web browser (next to config.xml, objects, symbols) then the error disappears. 

Info: I assume that I should find the other xql files from numishare/xforms/xquery here as well.

**Comment by ewg118** [comment]
I'm going to close this since it seems to have been resolved by uploading the XQL files into the database. I will look closer into this. It seems that perhaps there have been some slight changes in the eXist-db function that stores XQL into a collection. I am running the most current stable eXist-db on my laptop, and it didn't store the XQL files after the "Create New Collection" workflow.
