### ISSUE TITLE
Carrige Return and Tabs in csv 

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#54]
Create a collection with one or two simple coins with a reference.
View the public Site and click on the "CSV" icon.
A CSV query.csv is created. The output has "refernce string" like:
"CR TAB TAB TAB TAB TAB myReference String CR TAB TAB TAB TAB"

[query (11).zip](https://github.com/ewg118/numishare/files/1872764/query.11.zip)

**Comment by ewg118** [comment]
This is a result of changes in NUDS--the editing interface no longer creates references that are valid to the current schema. The nuds:reference now accepts mixed content within the TEI namespace. Therefore, the references are not indexed into Solr correctly, hence the carriage returns.

**Comment by Msch0150** [comment]
Now the CSV export works as expected for new created items. Thanks!
