### ISSUE TITLE
Recommended way to import coins

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#55]
What is the recommended (best practice) way to import several hundred coins?
These coins are currently in an Access DB. I see that there are some routines to import a CSV from Filemaker into mantis. If this is the recommended way, do you have an example CSV file with a couple of roman coins?

**Comment by ewg118** [comment]
The only way is to write a script that transforms CSV into NUDS XML compliant with the schema. The Mantis script is not reusable because it is written for the ANS FileMaker Pro curatorial database.
