### ISSUE TITLE
OCRE RIC (second edition) Augustus 385

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#61]
This is more content related, but I couldn't find any hint whom to contact regarding OCRE.

http://numismatics.org/ocre/id/ric.1(2).aug.385

Reverse legend is noted as: "L SVRDINVS IIIVIR A A A F F" (like 384), but in RIC I² it is noted as:

"L NAEVIVS L SVRDINVS IIIVIR A A A F F"

**Comment by ewg118** [comment]
The point of contact for corrections to CRRO and OCRE is Lucia Carbone, lcarbone@numismatics.org

**Comment by Msch0150** [comment]
Thanks! Email sent.
