### ISSUE TITLE
Web Resource doesn't accept IP address

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#63]
Create a coin in a collection.
Typological Description > check "Web Resource" > enter "http://numismatics.org/collection/1944.100.78380"  > hit TAB-key > the red icon "Required must be URI" disappears. > all  fine.
Now try again with "http://161.47.117.67/collection/1944.100.78380" which is using the IP address instead of the FQDN > hit TAB-key > the red-icon does not appear.

The above example should only show that the URI check on the page does not work with IPs.

**Comment by Msch0150** [comment]
Info: IPs are used in the test environment (together with docker) here.

**Comment by ewg118** [comment]
While technically not disallowed, I don't recommend point the typeDesc for a physical specimen in NUDS to the URI/typeDesc for another physical specimen. This feature is intended for linking a physical coin to a published coin type.

**Comment by Msch0150** [comment]
You are right. The above was a bad example. The fix helps me to make tests with a local cointype numishare server.
