### ISSUE TITLE
OCRE API examples not working

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#66]
(Minor issue)
http://numismatics.org/ocre/apis#getNuds

Try the mentioned example:

http://numismatics.org/ocre/apis/getNuds?identifiers=ric.4.ss.283B%7Cric.4.ss.283B%7Cric.4.ph_i.75A%20(a)

The page reports:
Orbeon Forms - An Error has Occurred

That is due to the fact, that the example coins do not exist in OCRE:

ric.4.ss.283B (given twice in the example, should appear only once, seems to be working without the "B" like "ric.4.ss.283")
ric.4.ph_i.75A%20(a) (works without the %20 like "ric.4.ph_i.75A(a)")

So  this works as an example:

http://numismatics.org/ocre/apis/getNuds?identifiers=ric.4.ss.283%7Cric.4.ph_i.75A(a)

Similar issue for RDF.

**Comment by ewg118** [comment]
There were several outlying Solr documents that contained only recordIds and no further metadata (and no NUDS documents in the XML database), which were somehow coming up as the examples in the API. I deleted these deprecated documents from Solr, so the API example functions correctly now.
