### ISSUE TITLE
"uncertain_value" unavailable in other languages

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#70]
Might be tricky ...

Admin UI: Create a coin > Authority + > "Honorius" > "Authority" > Certainity + > "Uncertain value" > Save
Display the coin in the UI:

Authority: Honorius (uncertain_value)

Now change language to "German":

Autorität: Honorius (uncertain_value)

So, there is not translation for "uncertain_value".

**Comment by ewg118** [comment]
This can be done in theory if I extend the drop down menu to link more directly to the Nomisma URI, and then write some code to use the preferred label from Nomisma for the URI instead of simply displaying the literal value of the certainty XML attribute.
