### ISSUE TITLE
Hide map

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#72]
I tried to hide the map but without success.

Admin UI > modify settings > map baselayers > uncheck all > save.

Now a blank "map" with legend etc is displayed. 
Probably it is not possible to do it in this way. Is there another way to hide the complete map?

Just for info: if no map is checked, the images of the coin don't get displayed anymore.

**Comment by ewg118** [comment]
I had never tested disabling the map outright. The map will always display as long as there's a mint or findspot with coordinates. I updated the code for the HTML page for an additional geoEnabled variable that will disable maps if all baselayers are unchecked in the config.

**Comment by Msch0150** [comment]
Works. Thanks!
