### ISSUE TITLE
Using SubjectSet

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#73]
We have several cases where findspots have roman greek and celtic coins.
So I want to add "something" so that numishare shows that this particular coins is a roman, greek or celtic one.
I want to use something from nomisma. So I tried in descMeta:

    <subjectSet>
        <subject xlink:href="http://nomisma.org/id/greek_numismatics" xlink:type="simple"></subject>
    </subjectSet>

I expected that numishare would display by default: "Greek Numismatics" but it shows the icon for the link only. Of course I can add "Greek coin" as text but that is not language sensitive, both get displayed:

    <subjectSet>
        <subject` xml:lang="en">Greek coin</subject>
        <subject xml:lang="de">Griechische Münze</subject>
    </subjectSet>

Bug? Feature? I'm in doubt. Maybe there is already something which I can use, but I couldn't find it.

**Comment by ewg118** [comment]
The subjectSet is underutilized so far, but it would be useful to be able to link it to Nomisma-defined fields of numismatics, which would solve your problem. However, I think that all of the fields of numismatics have only English labels so far. I will see what I can do this week to extend the subjects to support a drop down menu of Nomisma terms. There isn't one for Celtic numismatics, but it needs to be created.

**Comment by ewg118** [comment]
Using a Nomisma URI for a field of numismatics would work in theory, if the concepts were multilingual in Nomisma itself. I will send an email to the Nomisma list to see if people will offer to translate these.
