### ISSUE TITLE
descriptionSet > description

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#74]
http://nomisma.org/nuds#descriptionSet

I made a couple of tests to display a general description via descriptionSet. Unfortunately I didn't get it to work. Is it implemented in numishare? Do I make a mistake? I attached an example.

[20000000-001.xml.txt](https://github.com/ewg118/numishare/files/2526909/20000000-001.xml.txt)

**Comment by ewg118** [comment]
No, I don't think I have gotten around to implementing the descriptionSet yet. I'll add it to the to-do list for when I finish publishing a current project.

**Comment by ewg118** [comment]
Note that the editing interface only allows free text in each `nuds:description` element. The XSD schema allows mixed content with 0 or more `nuds:ab` (anonymous block) elements that allow for any paragraph element namespaced from TEI. Mixed content is difficult to handle in XForms, so it probably won't be implemented in the back-end.
