### ISSUE TITLE
Subtype of Suptype not visible/searchable

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#81]
Create a collection of type "Collection Type".
Create a coin type "nemausus".
Create a another coin type "nemausus_1".  Set Publication Status to "approvedSubtype". Select "nemausus" as parent type Record ID.
Create a another coin type "nemausus_1_1".  Set Publication Status to "approvedSubtype". Select "nemausus_1" as parent type Record ID.

Now browser the collection on the regular site. 
"nemausus" and "nemausus_1" but "nemausus_1_1" is not displayed.
Also a search for "nemausus" will display the"nemausus" and "nemausus_1" only, but not "nemausus_1_1".

**Comment by ewg118** [comment]
I am surprised nemausus_1 is being displayed. Although subtypes are indexed and can be queried through the Atom feed or the OpenRefine reconciliation API, the HTML-based result pages only display top-level parent types. I don't have plans on changing this--or at least make each subtype a row in the result set.

**Comment by Msch0150** [comment]
Thanks for the hint.
