### ISSUE TITLE
Issues with digital representation (may be local to us)

### ISSUE THREAD

**Issue by clarerowan** [ewg118/numishare#82]
The Image Upload form in Orbeon uploads the file fine, but doesn't give the user a confirmation that it's worked. And subsequently, the coin will not save as it says:
"Save Error. Are all required inputs filled?"
But there are no visible error messages.

**Comment by denseflux** [comment]
Update: We have this now working.

We discovered two separate reasons we were having trouble with this. Firstly, our IIIF server wasn't working as intended (we were using Canteloupe). The form updates to show the local files selected, but only with a working IIIF server, does the action on the upload button return a success, and fill out the NUDS. At which point the "Save Error" goes away.

Secondly, our Orbeon version wasn't in-step with the version the Numishare admin console depends upon, and this was causing the Digital Representation tab to misbehave.

This issue can be closed.

**Comment by ewg118** [comment]
OK. I noticed recently there was some issue with the tabs in Orbeon 2018+, so I had to revert to the old tab component system.
