### ISSUE TITLE
Triplestore (Apache Jena Fuseki) (may be local to us)

### ISSUE THREAD

**Issue by clarerowan** [ewg118/numishare#84]
There are no specimens fetched in the types browse interface, which gives me the suggestion that it’s not connected properly with Numishare, and it's not clear how to get the automated updating working (as above).
(We have discussed an issue with Fuseki 3 on Tomcat 7. We run CentOS 7.0.36. It's not clear whether this is indeed an issue in this case.

**Comment by ewg118** [comment]
I have found that Fuseki 3 requires Tomcat 8+. I'd downgrade Fuseki to 2.x or migrate to Tomcat 8. There are some minor variations in the installation of Numishare in Tomcat 7 vs. 8, which I have detailed in the Numishare wiki.

**Comment by ewg118** [comment]
Is your SPARQL endpoint accessible from outside Warwick?

**Comment by denseflux** [comment]
Not at the moment I’m afraid.

Sent from my mobile

________________________________

**Comment by ewg118** [comment]
I think this has been pinpointed to URI incongruencies / local configuration / minor data errors.
