### ISSUE TITLE
Re-index Published Objects

### ISSUE THREAD

**Issue by clarerowan** [ewg118/numishare#85]
“Error getting Solr document from XQuery ingestion pipeline.” When re-indexing published specimens
The SOLR index last updated changes, which could indicate it’s working… but the findspot data only seemed to work when a specimen was directly updated.

**Comment by ewg118** [comment]
Is there any chance that you can use the eXist-db client to back up your XML collection and email it to me? There is probably some XSLT error that's breaking this ingestion pipeline, but I can't troubleshoot it without having the data.

**Comment by ewg118** [comment]
I don't seem to be having this problem with the re-indexed published changes with either the specimens or tokens collection. I have changed some data and XSLT, so it's difficult to know what it is I might have fixed.

**Comment by ewg118** [comment]
I think this is resolved, but please let me know if you still get errors.
