### ISSUE TITLE
Match image URIs with matches() instead of contains()

### ISSUE THREAD

**Issue by ewg118** [ewg118/numishare#88]
@denseflux

The RDF at https://coins.warwick.ac.uk/token-specimens/id/fregdomus1.rdf is missing the image URI for the WebResource. After checking the XSLT, the conditional looks for 'http://' in the contains() function (literal string match) rather than the matches(., 'https?://'), which is more flexible in that it uses regex.

**Comment by ewg118** [comment]
I believe I have fixed the issue in my recent code push, but it needs to be tested on https image URLs.

**Comment by denseflux** [comment]
Yes, indeed. That's fixed the problem. Thanks

**Comment by ewg118** [comment]
OK. You may need to purge and reload the triplestore since this coin shows up in the specimen example list multiple times, so there must be some duplicate triples related to the specimen in the triplestore creating multiple results in the SPARQL response. 

If you can execute a SPARQL/Update through the UI for your endpoint (rather than deleting the triplestore data and starting over from scratch), you can delete an entire dataset with the following SPARQL query: https://gist.github.com/ewg118/449595d67c613ec1710334154ffbaaf0

replacing `DATASET` with the URI that you use to define the void:Dataset in your VoID RDF file.
