### ISSUE TITLE
Specimen findspot URLs error in Types collection

### ISSUE THREAD

**Issue by denseflux** [ewg118/numishare#89]
https://coins.warwick.ac.uk/token-specimens/id/romekircheriano4 produces the following RDF/XML triple:
```<nmo:hasFindspot` rdf:resource="https://coins.warwick.ac.uk/token-specimens/id/romekircheriano4#findspot"/>```
Yet the URL for the findspot URL presented in the type https://coins.warwick.ac.uk/token-types/id/TURS3586 is https://coins.warwick.ac.uk/token-specimens/findspot/d945103bb105dd97f12cd163103776d1 which does not resolve.

**Comment by ewg118** [comment]
This change will necessitate reindexing the token specimens in Solr.
