### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by pasks87** [ewg118/numishare#90]
I'm having problems with the installation. I put on numishare with orbeon on my xampp instance by downloading the package from the master and I followed all the instructions. At the end I always get this message when I go to http://localhost:8080/orbeon/numishare "You are seeing this interface either because authentication has not been enabled for the Numishare administrative panel or there is no matching eXist-db collection for your role. If it is the latter case, please log in as the numishare-admin role and create a new collection for the associated Tomcat role."

**Comment by ewg118** [comment]
What version of Tomcat is packaged in xampp? There should be at least one user set to a `numishare-admin` role in order to enter the admin panel and set up the remaining installation process: https://github.com/ewg118/numishare/wiki/Tomcat-Authentication

**Comment by pasks87** [comment]
yes i set only one user for `numishare-admin`. this is my code:

```
<role rolename="manager-gui"/>
<role rolename="numishare-admin"/>
<role rolename="ocre"/>
<user username="tomcat" password="" roles="manager-gui"/>
<user username="admin" password="" roles="numishare-admin"/>
<user username="ocre-user" password="" roles="ocre"/>
```

**Comment by ewg118** [comment]
It seems like the /admin/ portion of Orbeon hasn't been locked down yet. Have you done https://github.com/ewg118/numishare/wiki/Tomcat-Authentication#restrict-access-to-numishareadmin-in-orbeon ? What version of Tomcat and Orbeon are you using? I have not tested the latest release of Orbeon, but the authentication instructions probably haven't changed.

**Comment by pasks87** [comment]
yes I have performed all the operations listed in the guide. The version of Tomcat is 7.0.92

**Comment by ewg118** [comment]
Assuming the logging has been activated, can you post a snippet from your orbeon.log for when you try to enter /orbeon/admin/ ? When you go to http://localhost:8080/orbeon/numishare/, it directs to http://localhost:8080/orbeon/numishare/admin/ correct?

**Comment by pasks87** [comment]
yes, i've done

**Comment by pasks87** [comment]
I tried to reinstall all the components but i counld not do the correct setting of platform. Could you help me, saying what are the correct version that i can use to build up the program? I want to use xampp to facilitate the sertting up of platform.
