### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by jtstratford** [ewg118/numishare#91]
I'm trying to run numishare, and I seem to be having issues similar to pask87. When I try to login, I see the message:

"You are seeing this interface either because authentication has not been enabled for the Numishare administrative panel or there is no matching eXist-db collection for your role. If it is the latter case, please log in as the numishare-admin role and create a new collection for the associated Tomcat role."

I am running Tomcat 7 on Ubuntu 16.04 LTS. I installed solr 4.10.4 from solr.war, exist 4.7.1 from exist.war, and the current release of Orbeon CE. Solr, Exist-db, and Orbeon all appear to be working correctly. I cloned numishare from github. I have notes on the installation below.

Thanks,
jtstratford

++++++++++++++++++++++++++++++++++++

/etc/default/tomcat
-rw-r--r-- 1 root root 2250 Nov 14 13:48 tomcat7

to include

JAVA_OPTS="-server -Djava.awt.headless=true -Xms2G -Xmx2G -XX:MaxPermSize=256m -XX:NewSize=896m -XX:MaxNewSize=896m -Dlog4j.configuration=/var/lib/tomcat7/lib/log4j.properties"
JAVA_OPTS="${JAVA_OPTS} -XX:+UseConcMarkSweepGC -XX:+CMSPermGenSweepingEnabled -XX:+CMSClassUnloadingEnabled"

Running Orbeon CE 2019.1.0 - installed from orbeon.war

Created orbeon.xml 

in $TOMCAT_HOME/conf/Catalina/localhost
In Tomcat 7: Insert the following XML fragment (substituting ”/var/lib/tomcat7” with $TOMCAT_HOME if necessary): <Context path="/orbeon" docBase="/var/lib/tomcat7/webapps/orbeon" allowLinking="true"/> 

In /var/lib/tomcat7/webapps/orbeon/WEB-INF/resources/config
-rw-r--r-- 1 tomcat7 tomcat7 5270 Nov 14 14:15 log4j.xml

uncommented
    <category name="org.orbeon.oxf.xforms.processor.XFormsServer">
        <priority value="debug"/>
    </category>

-rw-r--r-- 1 tomcat7 tomcat7  888 Nov 15 13:06 properties-local.xml

added

    <property as="xs:string" name="oxf.fr.authentication.method" value="container"/>
    <property as="xs:string" name="oxf.fr.authentication.container.roles"  value="other-project-roles numishare-admin"/>

    <property as="xs:NMTOKENS" name="oxf.xforms.logging.debug">
        document
        model
        submission
        control
        event
        action
        analysis
        server
        html
        process
    </property>

    <property as="xs:NMTOKENS" name="oxf.xforms.logging.error">
        submission-error-body
    </property>

Cloned Numishare from Github
    renamed Numishare to numishare

/var/lib/tomcat7/webapps/orbeon/WEB-INF/resources/apps
lrwxrwxrwx 1 root    root      29 Nov 14 14:24 numishare -> /usr/local/projects/numishare

solr 4.10.4 - installed from solr.war

Created solr.xml in

/var/lib/tomcat7/conf/Catalina/localhost
rw-r--r-- 1 root root 258 Nov 14 15:10 solr.xml

<?xml version="1.0" encoding="UTF-8"?>
<Context docBase="/var/lib/tomcat7/webapps/solr.war" debug="0" crossContext="true"> 
<Environment name="solr/home" type="java.lang.String" value="/usr/local/projects/numishare/solr-home" override="true"/> 

Created solr.xml in 
/var/lib/tomcat7/webapps/orbeon/WEB-INF/resources/apps/numishare/solr-home
root@hadestown:/var/lib/tomcat7/webapps/orbeon/WEB-INF/resources/apps/numishare/solr-home

-rw-r--r-- 1 root root 1276 Nov 14 12:53 solr.xml

<?xml version="1.0" encoding="UTF-8" ?>

<solr persistent="false">
	
	
	<cores adminPath="/admin/cores">
		<core name="numishare-published" instanceDir="1.5"/>
	</cores>
</solr>

exist 4.7.1 - installed from exist.war

Created exist-config.xml in
/var/lib/tomcat7/webapps/orbeon/WEB-INF/resources/apps/numishare
root@hadestown:/var/lib/tomcat7/webapps/orbeon/WEB-INF/resources/apps/numishare
-rw-r--r-- 1 root root   510 Nov 14 12:53 exist-config.xml

<?xml version="1.0" encoding="UTF-8"?>

<exist-config>
	<username>admin</username>
	<password></password>
	<url>http://localhost:8080/exist/rest/db/</url>
</exist-config>

**Comment by ewg118** [comment]
Can you post the tomcat7/webapps/orbeon/WEB-INF/web.xml?

Is there a login window when you go to 	http://localhost:8080/orbeon/numishare/admin/ or is it the same error message?

**Comment by jtstratford** [comment]
[web.xml.txt](https://github.com/ewg118/numishare/files/3860001/web.xml.txt)

In the past, I was seeing the login window. Right now, it's just going to the error message.

**Comment by jtstratford** [comment]
OK. I'm seeing

Numishare
The collections-list.xml file does not appear in the eXist-db collection, presumably becaues this is the first time you have run Numishare. Be sure to create the 'numishare-admin' Tomcat role following the instructions on Github. This page will automatically redirect to the admin panel in 10 seconds. If it does not, click here.

**Comment by ewg118** [comment]
Oh, wait a minute. The Tomcat and Orbeon version compatibility could be an issue here: https://doc.orbeon.com/installation/tomcat

On my desktop computer and in production, we are using Orbeon 2018.2. On my desktop, I have Tomcat 8.5 and on the production server, it's Tomcat 8.0. Tomcat 7 is fairly old now (2012 or so), and Orbeon isn't supported on Tomcat7 since 2017.2. I think it would be a good idea to run Tomcat 8.5 or 9. Tomcat 8.0 is in the Ubuntu 16.04 package manager, but Apache ended support for it already. Technically, you might be able to get Orbeon 2019.1 running on Tomcat 8, but I'm not sure. If nothing else, Orbeon 2018.2 will run fine.

**Comment by ewg118** [comment]
This might be related to #90

**Comment by ewg118** [comment]
The web.xml looks fine to me for BASIC authentication (the popup window).

**Comment by jtstratford** [comment]
Thanks. I'll take a look at the Tomcat and Orbeon installations, and let you know if I have any other questions.

**Comment by jtstratford** [comment]
Quick question. I've installed tomcat 8.5 and orbeon 2018. So far, so good. I'm able to bring up orbeon. I'm not finding $TOMCAT_HOME/conf/Catalina/localhost (location for orbeon.xml) in my tomcat 8.5 installation. Can you point me in the right direction? Thanks.

**Comment by ewg118** [comment]
You should be able to create $TOMCAT_HOME/conf/Catalina/localhost for orbeon.xml and solr.xml, and it will still work.

**Comment by jtstratford** [comment]
Thank you so much for your help earlier. I really appreciate it.
Since writing about this on Monday, I have upgraded Tomcat and downgraded Orbeon.

I created, and am using, the directory $TOMCAT_HOME/conf/Catalina/localhost 

At present, I'm trying to run numishare on

Ubuntu 16.04
Tomcat 8.5
Orbeon CE 2018
exist-db 4.71
solr 4.10.4

At this point Tomcat, Orbeon, exist, and solr appear to be working.

I cloned the Github Numishare repositry.

I'm still having a problem with authentication

http://localhost:8080/orbeon/numishare/

First time through, tomcat hands off to login, but not after

http://localhost:8080/orbeon/numishare/admin/

HTTP Status 403 - Access to the requested resource has been denied

Also, I was unable to figure out how to configure the virtual machine under tomcat 8.5. I was unable to see the environment variables for JAVA_OPTS, using printenv. I tried looking at this by restarting tomcat, and by trying to execute setenv.sh from /bin/sh . Should I be able to see the environment variables?

I am attaching 
/webapps/orbeon/WEB-INF/web.xml and 
/conf/tomcat-users.xml

As this is not a public server, the information in tomcat-users.xml is not hidden.

Thank very much for all your help.

[tomcat-users.xml.txt](https://github.com/ewg118/numishare/files/3870720/tomcat-users.xml.txt)
[web.xml.txt](https://github.com/ewg118/numishare/files/3870723/web.xml.txt)

**Comment by ewg118** [comment]
I believe the issue might be here:
```
<role rolename="numishare-admin"/>
<role role-name="other-project-roles"/>
<user username="admin" password="" roles="numishare-admin,other-project-roles"/>
```

The person who is the super-administrator for Numishare shouldn't be given other roles. The other roles are more for editors of particular, existing projects, while the Numishare admin can create or edit any project and modify the settings for any particular Numishare project.

The "admin" user should just have the roles="numishare-admin". The `role-name` attribute should be changed to `rolename`. I'm not sure what effect this error might have.

**Comment by jtstratford** [comment]
I'm running eXist-db-4.7.1 created from a .war file in tomcat 8.5.5, and I'm getting errors "unable to process jar entry [module-info.class] for annotations."  I was wondering which version of exist-db you were using.

Any thoughts appreciated. Thanks.

**Comment by jtstratford** [comment]
Numishare crashed with user "admin." Changed name, problem solved.
