### ISSUE TITLE
Import records from MANTIS to local Numishare

### ISSUE THREAD

**Issue by jtstratford** [ewg118/numishare#93]
We have Numishare up and running on a local machine.  We would like to be able to import a small subset of records from MANTIS and then add records for additional coins in SNGs and other sources.  Is there a way to export the records from MANTIS in Atom and then get the local Numsihare instance to add them to a collection.  Any guidance on an automated or semi-automated way to do this would be appreciated.

**Comment by ewg118** [comment]
The Atom feed should contain a link to the NUDS/XML file (which you get just by appending .xml onto the URI for a coin). If you devise a script that iterates through each page of the Atom response, you should be able to either download each XML file and upload them all in a batch through the eXist-db client into the Numishare collection or (probably easier) use CURL in your script to PUT them into eXist-db. In PHP, that looks like this: https://github.com/ewg118/numishare/blob/mantis2/script/fm-to-nuds.php#L178

**Comment by jtstratford** [comment]
This answered my question. Thank you.
