### ISSUE TITLE
Browse Collection Screen Display

### ISSUE THREAD

**Issue by jtstratford** [ewg118/numishare#96]
On the Browse Collection screen, "Refine Results" is not displaying correctly, and Keyword and Date Range do not appear to be working. Is there a strategy for dealing with this?
![Numishare](https://user-images.githubusercontent.com/57914113/84536635-1a5a6580-aca3-11ea-9320-6643d50d7d7a.JPG)

Thank you.

**Comment by ewg118** [comment]
I think this is an issue with the URL path to the folder in which the Javascript and CSS are stored. I would double check the steps from https://github.com/ewg118/numishare/wiki/Numishare-Themes

**Comment by jtstratford** [comment]
That fixed it. Thank you
