### ISSUE TITLE
Nomisma lookup results not appearing

### ISSUE THREAD

**Issue by denseflux** [ewg118/numishare#98]
I'm trying to debug this edit coin issue:

![region_lookup](https://user-images.githubusercontent.com/2453698/92131889-62021080-edfe-11ea-886f-1a625af15e97.png)

Upon execute, I get a response from xforms-server that there are results (and this changes depending on the query). However the response is otherwise empty.

Seemed to break without intervention, so wondering if the issue is around content negotiation with nomisma.org and changes beyond numishare itself?

Help of where to look to debug would be welcomed, please?

**Comment by ewg118** [comment]
I fixed this. The link to the html page in the Atom feed was recently updated to be `rel="canonical"`, but the code for the entity lookup was looking for a link without a `rel` at all. You'll want to pull the changes from xforms/xbl/entity-input/entity-input.xbl

**Comment by denseflux** [comment]
That's great. Thanks, Ethan.
